# Generated by Django 5.1.2 on 2024-11-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
